(library
 (name refined_ir)
 (public_name refined_ocaml.ir)
 (modules
  source_span
  refined_types
  typed_core
  logic_term
  relational_outcome
  function_analysis
  theory_slice
  evar_context
  horn_fixpoint
  generic_refinement
  refinement_domain
  typing_judgment
  vc_semantics))

(library
 (name refined_core)
 (public_name refined_ocaml.core)
 (modules
  refined_common
  proof_artifact_io
  ocaml_5_3_attributes
  ocaml_5_3_lowering
  ocaml_5_3_theory
  ocaml_5_3_rmi
  ocaml_5_3_frontend
  solver_backend
  vc_logic
  heap_model
  ownership
  vc_encoding
  pure_vc
  outcome_vc
  coverage_vc
  vc_backend
  refined_core)
 (private_modules
  ocaml_5_3_attributes
  ocaml_5_3_lowering
  ocaml_5_3_theory
  ocaml_5_3_rmi
  vc_logic
  heap_model
  ownership
  vc_encoding
  pure_vc
  outcome_vc
  coverage_vc)
 (libraries refined_ir compiler-libs.common digestif unix))
